# Default IOC prefix used for all bindings
prefix = "myIOCPrefix:"

# Can use either PV Access (pva) or Channel Access (ca)
provider = "ca"

# Character used to quit the program
quit = 'q'

# Execute these CA/PVA puts at the start of the program
put = [
    {pv="m1.DESC", value="Motor 1"},
    {pv="m1.HLM", value=100.0},
    {pv="m1.SPMG", value=3},
]

[keybindings]
key_right = {pv="m1.TWF", value=1}
key_left = {pv="m1.TWR", value=1}
key_up = {pv="m1.TWV", value=0.1, increment=true}
key_down = {pv="m1.TWV", value=-0.1, increment=true}
