# Default IOC prefix used for all bindings
# unless explcitly overriden
prefix = "namSoft:"

# Can use either PV Access (pva) or Channel Access (ca)
provider = "ca"

[keybindings]
key_right = {pv="m1.TWF"} # no value just means trigger
key_left = {pv="m1.TWR"} 
