# Default IOC prefix used for all bindings
# unless explcitly overriden
prefix = "namSoft:"

# Can use either PV Access (pva) or Channel Access (ca)
provider = "ca"

[keybindings]
key_a = {pv="m1.RBV", value=1}
key_b = {pv="m2.RBV", value=1}
# key_right = {pv="m1.TWF", value=1}
# key_left = {pv="m1.TWR", value=1}
